// Generated by LiveScript 1.4.0
var tests, i$, len$, test, ref$, result, expected, e, out$ = typeof exports != 'undefined' && exports || this, slice$ = [].slice;
out$.merge = merge;
function merge(obj1){
  var sources, i$, len$, obj2, p, e;
  sources = slice$.call(arguments, 1);
  for (i$ = 0, len$ = sources.length; i$ < len$; ++i$) {
    obj2 = sources[i$];
    for (p in obj2) {
      try {
        if (!(obj2[p] instanceof Object)) {
          throw null;
        }
        obj1[p] = merge(obj1[p], obj2[p]);
      } catch (e$) {
        e = e$;
        obj1[p] = obj2[p];
      }
    }
  }
  return obj1;
}
function pack(x){
  return JSON.stringify(x);
}
tests = [
  function(){
    var a, b, expected, result;
    a = {
      a: 1,
      b: 2,
      c: {
        ca: 1,
        cb: 2
      }
    };
    b = {
      c: {
        cb: 5
      }
    };
    expected = {
      a: 1,
      b: 2,
      c: {
        ca: 1,
        cb: 5
      }
    };
    result = merge(a, b);
    return {
      result: result,
      expected: expected
    };
  }, function(){
    var a, expected, result;
    a = {
      a: 1,
      b: 2,
      c: {
        ca: 11,
        cb: 2
      }
    };
    expected = {
      a: 1,
      b: 2
    };
    result = merge(a, {
      c: void 8
    });
    return {
      result: result,
      expected: expected
    };
  }, function(){
    var a, b, expected, result;
    a = {
      a: 1,
      b: 2,
      c: {
        ca: 11,
        cb: 2
      }
    };
    b = {
      c: {
        cb: 5
      }
    };
    expected = {
      a: 1,
      b: 2,
      c: {
        cb: 5
      }
    };
    result = merge(a, {
      c: void 8
    }, b);
    return {
      result: result,
      expected: expected
    };
  }
];
try {
  console.log("Starting tests...");
  for (i$ = 0, len$ = tests.length; i$ < len$; ++i$) {
    test = tests[i$];
    ref$ = test(), result = ref$.result, expected = ref$.expected;
    if (pack(result) !== pack(expected)) {
      throw null;
    }
  }
  console.log("Tests are OK...");
} catch (e$) {
  e = e$;
  console.log("Test failed: ", e);
}